steps:

- name: 'gcr.io/cloud-builders/gcloud'
  args: ['config', 'set', 'project', 'proyecto-bridge']

# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west2-docker.pkg.dev/proyecto-bridge/imagendocker/mongo:1.0', '-f', 'server/Dockerfile', '.']

# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west2-docker.pkg.dev/proyecto-bridge/imagendocker/mongo:1.0']

# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args: [
    "-c",
    "gcloud run deploy react-nodejs-cloudbuilds-server 
    --image=europe-west2-docker.pkg.dev/proyecto-bridge/imagendocker/mongo:1.0
    --region=europe-west1 
    --platform=managed 
    --allow-unauthenticated 
    --port=3000 
    --update-env-vars DB_URL_ATLAS=$$DB_URL_ATLAS"
  ]

  secretEnv: [
    'DB_URL_ATLAS'
  ]
images:
- 'europe-west2-docker.pkg.dev/proyecto-bridge/imagendocker/mongo:1.0'

availableSecrets:
  secretManager:
    - versionName: projects/958123269337/secrets/mongo/versions/1
      env: 'DB_URL_ATLAS'
